[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_realm = ${SAMBA_REALM}
 default_ccache_name = KEYRING:persistent:%{uid}

[realms]
 ${SAMBA_REALM} = {
  kdc = ${SAMBA_HOST_NAME}.${SAMBA_REALM,,}
  admin_server = ${SAMBA_HOST_NAME}.${SAMBA_REALM,,}
  default_domain = ${SAMBA_REALM,,}
 }

[domain_realm]
 .${SAMBA_REALM,,} = ${SAMBA_REALM}
 ${SAMBA_REALM,,} = ${SAMBA_REALM}